<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/css">
<meta name="Keywords" content="">
<link href="style.css" rel="stylesheet" type="text/css">
<link rel="shortcut icon" href="favicon.ico">
<title>Ask Jeff  - Question the Online Whiz from Aplus.net</title>
<script language="javascript">
<!--
 
function setAction()
{    
	i=document.Form.act_domain.selectedIndex;
	val=document.Form.act_domain.options[i].value;
	if(val==1) document.Form.action = "https://signups.aplus.net/cgi-bin/wairs/aplus.cgi";
	if(val==2) document.Form.action = "https://signups.aplus.net/cgi-bin/wairs/aplus.cgi";
	if(val==3) document.Form.action = "https://signups.aplus.net/cgi-bin/wairs/aplus.cgi";	
	document.Form.submit();
}

//-->
</script>





</head>

<body>
<table width="983" cellpadding="0" cellspacing="0" border="0" align="center">
	<tr valign="top">
    	<td align="left" width="12"><img src="images/left.jpg" alt=""></td>
        <td width="959" style="background-color:#FFFFFF;" align="center">
        	<!--Begin-->
            	<table width="946" align="center" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:25px;">
                	<tr valign="top">
                    	<td>
                        
                            <table width="940" cellpadding="0" cellspacing="0" border="0" style="margin-left:3px; height:110px;">
                                <tr valign="top">
                                    <td align="left">
                                        <div style="width:250px; padding-top:29px; float:left;"><a href="#" style="margin-left:9px;"><img src="images/logo.jpg" alt=""></a></div>
                                        <div style="margin-right:24px; padding-top:56px; text-align:right;" class="comm"><span class="blue"><script language="JavaScript">
                                homeDomain = window.document.domain +" "				  
                                cutDomain = homeDomain.split(".")
                                    if (cutDomain.length == 2){
                                        domainName=cutDomain[0]	
                                        TLD=cutDomain[1]							
                                    }else{
                                        domainName=cutDomain[1]	
                                        TLD=cutDomain[2]
                                    }
                                document.write(domainName+"."+TLD)
                                </script></span>&nbsp;coming soon!</div>
                                
                                    </td>
                                </tr>
                            </table>
                            
                          </td>
                    	</tr>
                    <tr valign="top">
                         	<td>
                            	<p style="margin-left:3px;"><img src="images/lin.jpg" alt=""></p>
                            	<table width="927" border="0" cellpadding="0" cellspacing="0" style="margin-left:15px;">
                                	<tr valign="top">
                                    	<td width="650">
                                        	<p class="name_txt" style="margin-top:20px;">Register, renew or transfer your <b>domain!</b></p>
                                            <form name="Form" method="post"  target="_blank" ><input type="hidden" name="languageSelect" value="en"><input type="hidden" name="pageid" value="index">
                                                <table border="0" cellpadding="0" cellspacing="0" style="margin-top:25px;">
                                                    <tr valign="top">
                                                        <td width="225"><p class="blue_14"><b>1. Choose a domain name</b></p></td>
                                                        <td><p class="blue_14"><b>2. Select an extension</b></p></td>
                                                    </tr>
                                                    <tr>
                                                    	<td class="text_f">
                                                        	<p class="black_11" style="margin-left:7px;">www. <input class="text_field" name="dname" value="" type="text"></p>
                                                        </td>
                                                        <td>
                                                        	<select name="tldSelect" class="black_11" style="width:110px;"> 
                                                              <option class="black_11">.com</option>
                                                              <option class="black_11">.net</option>
                                                              <option class="black_11">.org</option>
                                                              <option class="black_11">.biz</option>
                                                              <option class="black_11">.info</option>
                                                              <option class="black_11">.us</option>
                                                              <option class="black_11">.mobi</option>
                                                              <option class="black_11">.tv</option>
                                                              <option class="black_11">.cc</option>
                                                              
                                                      	  	</select>
                                                        </td>
                                                    </tr>
                                                    <tr valign="top">
                                                    	<td colspan="2" style="padding-top:22px;"><p class="blue_14"><b>3. Select domain status</b></p></td>
                                                    </tr>
                                                    <tr>
                                                    	<td>
                                                        	<select name="act_domain" class="black_11" style="width:154px;">
                                                            	<option class="black_11" value="1">New</option>
                                                                <option class="black_11" value="2">Transfer</option>
                                                                <option class="black_11" value="3">Renew</option>
                                                      	  	</select>
                                                        </td>
                                                        <td><input onClick="javascript: setAction();" type="image" src="images/reg_now.jpg"></td>
                                                    </tr>
                                                </table>
                                            </form>
                                        </td>
                                        <td><p><img src="images/right_pic.jpg" alt=""></p></td>
                                    </tr>
                                </table>
                                <div class="block1">
                                	<table border="0" cellpadding="0" cellspacing="0" style="margin-left:17px; margin-top:15px;">
                                    	<tr valign="top">
                                        	<td width="312">
                                            	<p class="blue_16"><b>Get your domain name FREE!</b></p>
                                                <p class="line_h18" style="margin-top:10px;">Sign up for any web hosting package from<br>Aplus.net to receive your new domain<br>name for free!</p>                                                                                         </td>
                                            <td width="312">
                                            	<p class="blue_16"><b>Web Design</b></p>
                                                <p class="list1" style="margin-top:10px;">SEO & Flash Options Available</p>
                                                <p class="list1" style="margin-top:5px;">Free Design Consultation</p>
                                                <p class="list1" style="margin-top:5px;">Website Live in 12 days</p>
                                                <p class="list1" style="margin-top:5px;">Design Plans Starting at $39.99/mo</p>
                                            </td>
                                            <td>
                                            	<p class="blue_16"><b>Web Hosting</b></p>
                                                <p class="list1" style="margin-top:10px;">30 Day Money-back Guarantee</p>
                                                <p class="list1" style="margin-top:5px;">99.9% Uptime Guarantee</p>
                                                <p class="list1" style="margin-top:5px;">24/7/365 Live Support</p>
                                                <p class="list1" style="margin-top:5px;">Starting at $4.46/mo</p>
                                                                                            </td>
                                        </tr>
                                    	<tr valign="top">
                                    	  <td valign="bottom">   <p style="margin-left:93px; vertical-align: middle;"><a href="http://www.aplus.net/hosting"><img src="images/sign_up_today.jpg" alt=""></a></p></td>
                                  	      <td width="312" valign="bottom"><p style="margin-left:100px; margin-top:15px;"><a href="http://www.aplus.net/web-design"><img src="images/learn_more_green.jpg" alt=""></a></p></td>
                                          <td valign="bottom"><p style="margin-left:100px; margin-top:15px;"><a href="http://www.aplus.net/hosting"><img src="images/learn_more_green.jpg" alt=""></a></p></td>
                                   	  </tr>
                                    </table>
                              </div>
                                <table border="0" cellpadding="0" cellspacing="0" style="margin-left:18px; margin-top:15px;">
                                	<tr valign="top">
                                    	<td colspan="3">
                                        	<p class="green_18"><b>Why choose aplus.net?</b></p>
                                            <p style="margin-top:10px;">The Aplus.net Advantage offers an exceptional hosting service for your online business. Our intuitive applications and services are designed to help you create a professional business and ecommerce-enabled website. Aplus.net is your source for a top of the market hosting experience. We offer high quality web hosting, email, web design, domain name registration, online marketing, and web applications, designed give your business an advantage over the rest.</p>
                                        </td>
                                    </tr>
                                	<tr valign="top">
                                    	<td width="430" style="padding-top:20px;">
                                        	<p class="green_18"><b>Low Cost Web Hosting:<br>The first step in online success.</b></p>
                                            <p style="margin-top:10px;">All Aplus.net web hosting accounts are housed in our highly secure data centers. Now you're set with the stability of Unix and the latest Microsoft® technology with Windows® Server 2008 on all our new Unix/Windows hybrid plans. Take advantage of domain name registration, multiple email accounts and online marketing tools. Also enjoy the added benefits of our 99.9% uptime and 30-day money-back guarantees with live 24/7/365 North American-based support! View our shared hosting plans.</p>
                                        </td>
                                        <td width="26"></td>
                                        <td width="455" style="padding-top:20px;">
                                        	<p class="green_18"><b>Professional website design at small<br>business-friendly prices.</b></p>
                                            <p style="margin-top:10px; margin-right:20px;">A great website starts with great design. Entice customers with a professionally designed website. To get started, simply browse the <a href="http://webdesign.aplus.net/templates/">web design template gallery</a> with more than 4,000 templates and choose the one that's right for your company!</p>
                                      </td>
                                    </tr>
                                    <tr valign="top">
                                    	<td width="430" style="padding-top:15px;">
                                        	<p align="right"><a href="http://www.aplus.net/hosting"><img src="images/learn_more_blue.jpg" alt=""></a></p>
                                        </td>
                                        <td width="26"></td>
                                        <td width="455" style="padding-top:15px;">
                                        	<p align="right" style="margin-right:20px;"><a href="http://www.aplus.net/design/"><img src="images/learn_more_blue.jpg" alt=""></a></p>
                                        </td>
                                    </tr>
                                    <tr valign="top">
                                    	<td width="430" style="padding-top:20px;">
                                        	<p class="green_18"><b>Marketing, ecommerce, and lead generation<br>tools for online success.</b></p>
                                            <p style="margin-top:10px;">Aplus.net recognizes your need to drive quality traffic to your site which is why we compliment our <a href="http://aplus.net/hosting/">web hosting</a> by offering online marketing tools. Make your site work harder for you and your customers with our powerful marketing tools!</p>
                                      </td>
                                        <td width="26"></td>
                                        <td width="455" style="padding-top:20px;">
                                        	<p class="green_18"><b>Every available domain name, plus every<br>possible alternative.</b></p>
                                            <p style="margin-top:10px; margin-right:20px;">Aplus.net offers superior domain name registration. Our low prices save you money, as some registrars charge up to $35 per year! With Apus.net, domains are free with hosting and we offer domain protection services to keep your business safe!</p>
                                        </td>
                                    </tr>
                                    <tr valign="top">
                                    	<td width="430" style="padding-top:15px;">
                                        	<p align="right"><a href="http://www.aplus.net/marketing"><img src="images/learn_more_blue.jpg" alt=""></a></p>
                                        </td>
                                        <td width="26"></td>
                                        <td width="455" style="padding-top:15px;">
                                        	<p align="right" style="margin-right:20px;"><a href="http://www.aplus.net/domains/
"><img src="images/learn_more_blue.jpg" alt=""></a></p>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                         </tr>
                        </table>
                        
                        <table width="959" border="0" cellpadding="0" cellspacing="0" class="bottom">
                        	<tr valign="top">
                            	<td align="right"><p><img src="images/bottom_right.jpg" alt=""></p></td>
                            </tr>
                        </table>
                         
            <!--END-->
        </td>
        <td align="left" width="12"><img src="images/right.jpg" alt=""></td>
    
    </tr>
</table>

<table width="959" border="0" cellpadding="0" cellspacing="0" align="center">
	<tr valign="top">
    	<td style="height:45px;">
        	<p align="right" class="copy_txt" style="margin-right:10px; margin-top:10px;">Copyright &copy; 1996-2009 Aplus.net Internet Services. All rights reserved.</p>
        </td>
    </tr>
</table>
   

</body>
</html>